title: "Chris Sansam's Portfolio"
description: "Showcasing my research and coding projects"
author: "Chris Sansam"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
navigation: main
atom_feed:
  path:
# Navigation Bar
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"
  - title: "About"
    url: "/about/"
footer_links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/sansamcl"
  #- label: "RSS"
  #  icon: "fas fa-rss"
  #  url: "/feed.xml"
